# Copyright Â© Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
kubeadmConfigPatches:
  - |-
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        oidc-client-id: k8s
        oidc-issuer-url: https://host.docker.internal:8443/realms/airm
        oidc-username-claim: email
        oidc-username-prefix: oidc
        oidc-groups-claim: groups
        oidc-groups-prefix: oidc
        oidc-ca-file: "/etc/kubernetes/pki/oidc/oidc-ca.crt"
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: .
        containerPath: /code
      - hostPath: ./services/airm/api/.kc-certs/tls.crt
        containerPath: /etc/kubernetes/pki/oidc/oidc-ca.crt
        readOnly: true
