# Copyright Â© Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: "airm-api"
    scrape_interval: 5s

    static_configs:
      - targets: ["host.docker.internal:9009"]
