# Copyright Â© Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

# Default values for gpu-job
image: busybox:latest
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
    amd.com/gpu: "2"
  limits:
    cpu: "100m"
    memory: "128Mi"
    amd.com/gpu: "2"
sleepDuration: 300
